### PR TITLE
chore(release): version 3.0.0

### LINKED ISSUE #761: [Features] Moderation logging
### Is your feature request related to a problem? Please describe.

I don't believe so, no.

### Describe the solution you'd like

Moderation logs to log moderation infractions. 

### Describe alternatives you've considered

Being able to set a modlog channel within the bot. 

### Additional context

_No response_

### LINKED ISSUE #764: [Features] New parser for some .env values
I have seen many user having trouble when it comes to setting some env value like alt prefix and owners. The value of these env value will be changed from JSON array to something that is simpler. It will be a list separated with comma or semicolon. For example, owners env value will be like this:

```
OWNERS="366169273485361153, 390045370240991234"
```

This would probably be easier to setup for basic user than using JSON array format. I'm still open to any new and probably better ideas for env value parsing. So, if you have any great idea you want to share for the value parsing, just comment on this issue.

### LINKED ISSUE #790: [Bug Report] Repeat command detail usage are not showing the actual value
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

image
add what these {options} are in help command
some people don't know how to use this command.
they just type xrepeat on. but it doesn't work so they try typing xhelp repeat (to know how to use it) but they can't find the options so it'd be better if u add something of the options in help command too

### Describe alternatives you've considered

_No response_

### Additional context

(sorry, i dont know how to explain this properly, I hope you understood)

### LINKED ISSUE #792: [Features] Debug logging mode
Create a debug log mode to help developers debug errors easier. The amount of logs shown in debug mode will be more than in development environment. Also, debug log mode will be allowed to be enabled in production environment.

### LINKED ISSUE #793: [Features] Use MessageFormat formatting feature for localizations
Apparently, MessageFormat has formatting features that we can use to check something like plural numbers and stuff. We will make use of this for some commands like purge and remove commands.

### LINKED ISSUE #830: [Features] Don't reset the Volume command when the track is ended
### Is your feature request related to a problem? Please describe.

It doesn't feel good if every song queue changes or ends, the queue volume is immediately reset to default or 100.

### Describe the solution you'd like

As the title said.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #848: [Features] Custom DJ and Mute role
Allow user to set their own DJ and Mute role.

### LINKED ISSUE #851: [Features] Replace youtube-dl-exec with our own stream module
Apparently, when some of our users trying to install modules for Rawon the NPM doesn't install `youtube-dl-exec`. Why? because they don't have Python on their machine. `"But you already added play-dl alternative right? So what's the problem?"` The problem is that when they're trying to build the project, `youtube-dl-exec` is trying to be imported in the `YTDLUtils.ts` by `ESLint`. Then, yes as you might've thought, since `youtube-dl-exec` is not installed on their machine ESLint detect it as `any`. This leads to ESLint error. So, the alternative that I come up with is that we move youtube-dl-exec into a single stream module file so that the `YTDLUtils` can still get the types of the stream module.

### PR DESCRIPTION
**Pull request by Mednoob**
Planned changes:
- [x] Change code structure and style.
- [x] Configure how to build this project using SWC (if possible, because SWC is far lower size than sucrase).

Duplicate of #746

### CODE REVIEW

**Comment by mzrtamp** [comment]
WHY THE GITHUB LINTER IS VERY STRESSING AND ANNOYING

**Comment by Mednoob** [comment]
For anyone wondering, the release time is probably gonna be 1 - 3 months later. We want to make sure that all features are implemented correctly and that Rawon can run with less errors in this version.

**Comment by mzrtamp** [comment]
Stress

**Comment by mzrtamp** [comment]
@lxndr-rl We're about going to merge this new version, so we need to do last touch. I need your hand here, to re-sync the `lang/es` file, I sense many changes happen to `lang/en` file 😊

**Comment by lxndr-rl** [comment]
> @lxndr-rl We're about going to merge this new version, so we need to do last touch. I need your hand here, to re-sync the `lang/es` file, I sense many changes happen to `lang/en` file 😊

Of course, no problem. Later, after I finish my things, I'll take a look at it

**Comment by mzrtamp** [comment]
> Of course, no problem. Later, after I finish my things, I'll take a look at it

Great, now you have a **Write access** into this repository!

**Comment by lxndr-rl** [comment]
Because it is a protected branch I opened a PR

**Comment by mzrtamp** [comment]
> Because it is a protected branch I opened a PR

Oh, my bad 😅

**Comment by mzrtamp** [comment]
You missed [something](https://github.com/Clytage/rawon/pull/944#pullrequestreview-988337778) @lxndr-rl 🙏

**Review by mzrtamp — APPROVED** [review]
Finally

**Comment by Mednoob** [comment]
Finally, v3 is done. It's a bit sooner than I expected. Even though it's because I moved some fixes and features to another version instead, but I'm glad still. Thank you, and good job everyone 🎉

**Pull request merged**
