### PR TITLE
chore(lang/es): synchronize with EN localization

### PR DESCRIPTION
**Pull request by lxndr-rl**
Additionally some strings have been fixed

### CODE REVIEW

**Review by mzrtamp — CHANGES_REQUESTED** [review]
Hi, thanks for the PR, but I sense you missed something

[cantMuteOwner](https://github.com/Clytage/rawon/blob/03b6bb9c75b16bf76cb9abe3762b0571bc5dc23f/lang/es.json#L123) and [noRole](https://github.com/Clytage/rawon/blob/03b6bb9c75b16bf76cb9abe3762b0571bc5dc23f/lang/es.json#L124)

**Comment by lxndr-rl** [comment]
> Hi, thanks for the PR, but I sense you missed something
> 
> [cantMuteOwner](https://github.com/Clytage/rawon/blob/03b6bb9c75b16bf76cb9abe3762b0571bc5dc23f/lang/es.json#L123) and [noRole](https://github.com/Clytage/rawon/blob/03b6bb9c75b16bf76cb9abe3762b0571bc5dc23f/lang/es.json#L124)

Done

**Comment by mzrtamp** [comment]
Thanks

**Review by mzrtamp — APPROVED** [review]
LGTM!

**Pull request merged**
