### PR TITLE
chore(release): version 2.4.0

### LINKED ISSUE #720: [Bug Report] youtu.be URLs doesn't work
gives error when I paste youtu.be links

Error: ❌ | That URL doesn't have any song data.

### PR DESCRIPTION
**Pull request by Mednoob**
The merge time is not determined yet. PR will be merged when we, maintainers think that the feature added to the PR is enough to create a new version. Feel free to open a PR to branch [`feat/2.4.0`](https://github.com/zhycorp/disc-11/tree/feat/2.4.0).

### CODE REVIEW

**Comment by mzrtamp** [comment]
**Merging cannot be performed now**, because the PR's author said that this commit is not tested. Using `play-dl`, the player won't start.

**Comment by Mednoob** [comment]
**Merge Requirement**
<strike>
- [ ] Change code structure to re-usable but also readable/understandable (by splitting functionalities into separate functions and remove the use of single-line)
</strike> (next version instead)

- [x] Fix play-dl issue (player suddenly stop after start playing)
- [x] Investigate youtu.be link issue

**Comment by Mednoob** [comment]
Merge Date: 6 or 7 February

**Review by mzrtamp — APPROVED** [review]
Good to go

**Comment by mzrtamp** [comment]
Moved to #745

**Pull request merged**
