### PR TITLE
chore(readme): add button for railway deployment

### PR DESCRIPTION
**Pull request by Tiramitzu**

### CODE REVIEW

**Review by Mednoob — APPROVED** [review]
LGTM

**Comment by KagChi** [comment]
doesnt railway ban music bots?

**Comment by Tiramitzu** [comment]
> doesnt railway ban music bots?

Which part of Railway Fair Use does Rawon violate, may I ask?

**Comment by Tiramitzu** [comment]
maybe its actually the music/video not the bot....

**Comment by KagChi** [comment]
> Which part of Railway Fair Use does Rawon violate, may I ask?

i said "music bots" they ban that

**Comment by KagChi** [comment]
> maybe its actually the music/video not the bot....

they said you cant "Hosting/Distribution of DMCA protected content", also hosting lavalink on their platform can get ban.

**Comment by KagChi** [comment]
the meaning of the ban here is your railway account.

**Comment by Mednoob** [comment]
Can you please make a pull request instead?

**Comment by Mednoob** [comment]
We will also try to look again through Railway ToS and fair policy

**Comment by Mednoob** [comment]
I just done reading the ToS and Fair Use of Railway. However, I couldn't find where Railway declares that they aren't allowing music bots to be hosted on their service. I found about the DMCA/Intellectual Property though, but we already added that to the disclaimers. If you have the document or pages which is the part of Railway where they declare music bots are not allowed to be used, please let me know. @KagChi

**Comment by KagChi** [comment]
> I just done reading the ToS and Fair Use of Railway. However, I couldn't find where Railway declares that they aren't allowing music bots to be hosted on their service. I found about the DMCA/Intellectual Property though, but we already added that to the disclaimers. If you have the document or pages which is the part of Railway where they declare music bots are not allowed to be used, please let me know. @KagChi

they did not said in their website. one of their admin dmed me "lavalink is violates their tos", and i see in their discord server that people asking for music bots support "why my project get ban". that i only know.

**Comment by KagChi** [comment]
image
image
image

**Comment by KagChi** [comment]
if the bot is not ytdl-based i think they fine about it.

**Comment by Tiramitzu** [comment]
and that's why, we added **Use at your own risk** note....

**Comment by Mednoob** [comment]
I think @KagChi haven't seen the disclaimer file I made two hours ago. You can check it here: [DISCLAIMERS.md](https://github.com/Rahagia/rawon/blob/feat/3.0.0/DISCLAIMERS.md). Thank you once again for notifying us about Railway Fair Use policy.

**Pull request merged**
