### PR TITLE
feat(lang): Added Ukrainian

### PR DESCRIPTION
**Pull request by RomaDevWorld**
Hello!

I added `uk.json` in `lang` folder with all the translations to Ukrainian language (based on `en.json`)

**Notice: I still need your help, because in some places I don't understand how the text is being formatted (I left comments in those lines)
Could you please provide me an example of how the text will look when it's send to a user? Just a screenshot or a code block**

While translating, I noticed some possible mistakes in `en.json` so I fixed them as well. If this was made intentionally, I'll revert it.

Stay safe! Thank you!

### CODE REVIEW

**Comment by RomaDevWorld** [comment]
As I didn't get any explanation about certain translations, I left them unchanged.

**Comment by Mednoob** [comment]
Hi @RomaDevWorld, thanks for the translation. I just checked the PR and looks good. Only one thing left tho, you haven't added the localization to [`src/config/index.ts`](https://github.com/clytage/rawon/blob/main/src/config/index.ts#L43) and [`.env_example`](https://github.com/clytage/rawon/blob/main/.env_example#L36). You can click the link I provided to see where you need to edit.

**Comment by RomaDevWorld** [comment]
Made the changes that you mentioned

**Review by mzrtamp — APPROVED** [review]

**Comment by mzrtamp** [comment]
@RomaDevWorld Thank you!

**Pull request merged**
